"""Initial schema from models

Revision ID: 4b1356e45cc9
Revises: 
Create Date: 2026-02-20 22:10:02.633241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app

# revision identifiers, used by Alembic.
revision: str = '4b1356e45cc9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column('users', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.models.database.GUID(),
               existing_nullable=False,
               postgresql_using='id::uuid')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    op.alter_column('sessions', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.models.database.GUID(),
               existing_nullable=False,
               postgresql_using='id::uuid')
    op.alter_column('sessions', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=app.models.database.GUID(),
               existing_nullable=False,
               postgresql_using='user_id::uuid')
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('sessions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_sessions_session_key'), 'sessions', ['session_key'], unique=True)
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    
    op.alter_column('templates', 'id',
               existing_type=sa.CHAR(length=32),
               type_=app.models.database.GUID(),
               existing_nullable=False,
               postgresql_using='id::uuid')
    op.alter_column('templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('templates', 'created_by',
               existing_type=sa.CHAR(length=32),
               type_=app.models.database.GUID(),
               existing_nullable=True,
               postgresql_using='created_by::uuid')
    op.create_index(op.f('ix_templates_is_active'), 'templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_templates_name'), 'templates', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'id',
               existing_type=app.models.database.GUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.drop_index(op.f('ix_templates_name'), table_name='templates')
    op.drop_index(op.f('ix_templates_is_active'), table_name='templates')
    op.alter_column('templates', 'created_by',
               existing_type=app.models.database.GUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=True)
    op.alter_column('templates', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('templates', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('templates', 'id',
               existing_type=app.models.database.GUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_index(op.f('ix_sessions_session_key'), table_name='sessions')
    op.alter_column('sessions', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('sessions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('sessions', 'user_id',
               existing_type=app.models.database.GUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('sessions', 'id',
               existing_type=app.models.database.GUID(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###
