"""Add template_id foreign key to assets_data

Revision ID: 51f476513e32
Revises: e65e73434410
Create Date: 2026-02-28 06:18:39.776634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51f476513e32'
down_revision: Union[str, Sequence[str], None] = 'e65e73434410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets_data', 'template_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'assets_data', 'templates', ['template_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assets_data', type_='foreignkey')
    op.alter_column('assets_data', 'template_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
