"""add user permissions

Revision ID: 769b69bcfc31
Revises: 4b1356e45cc9
Create Date: 2026-02-21 08:32:11.443380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '769b69bcfc31'
down_revision: Union[str, Sequence[str], None] = '4b1356e45cc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isadmin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('can_view_templates', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('can_edit_template', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('can_delete_template', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('can_view_pdf', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('can_delete_pdf', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('can_create_pdf', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_users_isadmin'), 'users', ['isadmin'], unique=False)
    # ### end Alembic commands ###

    # --- Custom Data Migration ---
    # Give all permissions to the 'admin' user
    op.execute("""
        UPDATE users SET 
            isadmin = true,
            can_view_templates = true,
            can_edit_template = true,
            can_delete_template = true,
            can_view_pdf = true,
            can_delete_pdf = true,
            can_create_pdf = true
        WHERE username = 'admin'
    """)

    # Give specific default permissions to all other users
    op.execute("""
        UPDATE users SET 
            isadmin = false,
            can_view_templates = false,
            can_edit_template = false,
            can_delete_template = false,
            can_view_pdf = true,
            can_delete_pdf = false,
            can_create_pdf = false
        WHERE username != 'admin'
    """)
    # -----------------------------


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_isadmin'), table_name='users')
    op.drop_column('users', 'can_create_pdf')
    op.drop_column('users', 'can_delete_pdf')
    op.drop_column('users', 'can_view_pdf')
    op.drop_column('users', 'can_delete_template')
    op.drop_column('users', 'can_edit_template')
    op.drop_column('users', 'can_view_templates')
    op.drop_column('users', 'isadmin')
    # ### end Alembic commands ###
