"""Add assets_data table

Revision ID: e0e3f41f7cf0
Revises: 769b69bcfc31
Create Date: 2026-02-24 16:35:57.795346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0e3f41f7cf0'
down_revision: Union[str, Sequence[str], None] = '769b69bcfc31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
from app.models.database import GUID

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets_data',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('template_id', GUID(), nullable=False),
    sa.Column('asset_id', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_data_template_id'), 'assets_data', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_data_template_id'), table_name='assets_data')
    op.drop_table('assets_data')
    # ### end Alembic commands ###
