"""Add template_id to certificates

Revision ID: e65e73434410
Revises: 7cb9cb548478
Create Date: 2026-02-28 06:01:23.677122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.database


# revision identifiers, used by Alembic.
revision: str = 'e65e73434410'
down_revision: Union[str, Sequence[str], None] = '7cb9cb548478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('template_id', app.models.database.GUID(), nullable=True))
    op.create_foreign_key(None, 'certificates', 'templates', ['template_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'certificates', type_='foreignkey')
    op.drop_column('certificates', 'template_id')
    # ### end Alembic commands ###
